project:
  type: website
  output-dir: docs

website:
  title: "BSC_project_IPFS2023"
  navbar:
    right:
      - about.qmd
      - sylabus.qmd
      - text: Moodle
        href: https://moodle.hu-berlin.de/course/view.php?id=110830
format:
  html:
    theme: minty
    css: morph.scss
    # css: styles.css

editor: visual

